import type { Project } from './types'

/**
 * PORTFOLIO — PLACEHOLDER ENTRIES.
 * These records demonstrate the content structure only. They are NOT real projects
 * and are rendered with a visible "Примерен обект" label. Replace each one with a real,
 * completed project (title, location, materials, services, photos) and remove `isPlaceholder`.
 */
const note = 'Примерен запис — заменете с реален изпълнен обект.'

export const projects: Project[] = [
  {
    id: 'p-01',
    slug: 'primeren-obekt-ofis-sgrada',
    title: 'Офис сграда',
    location: { city: 'София' },
    type: 'office',
    materials: ['al-bond', 'hpl'],
    services: ['proektirane', 'dostavka', 'montazh', 'al-bond-montazh'],
    summary: 'Вентилируема фасада от Al Bond касети с HPL акценти.',
    description: `${note} Опишете обекта в 2–3 изречения: какво е, какъв е мащабът и каква е ролята на фирмата.`,
    challenge: 'Опишете основното предизвикателство: срокове, геометрия, работа на височина, обект в експлоатация…',
    solution: 'Опишете избраното решение: материал, система, начин на монтаж и защо.',
    execution: ['Замерване и разкрой', 'Изработка на касетите', 'Монтаж на подконструкция', 'Монтаж на облицовката'],
    cover: { alt: 'Офис сграда с фасада от Al Bond — placeholder', tone: 'acp-silver', seed: 1 },
    gallery: [
      { alt: 'Общ изглед — placeholder', tone: 'acp-silver', seed: 2 },
      { alt: 'Детайл на касети — placeholder', tone: 'acp-graphite', seed: 3 },
      { alt: 'HPL акценти — placeholder', tone: 'hpl-wood', seed: 4 },
      { alt: 'Входна зона — placeholder', tone: 'mixed', seed: 5 },
    ],
    technicalDetails: [],
    featured: true,
    isPlaceholder: true,
  },
  {
    id: 'p-02',
    slug: 'primeren-obekt-zhilishtna-sgrada',
    title: 'Жилищна сграда',
    location: { city: 'Пловдив' },
    type: 'residential',
    materials: ['hpl'],
    services: ['hpl-fasadi', 'ventiliruemi-fasadi', 'montazh'],
    summary: 'HPL вентилируема фасада с дървесен декор.',
    description: `${note} Опишете обекта, етажността и обхвата на изпълнението.`,
    challenge: 'Опишете предизвикателството.',
    solution: 'Опишете решението.',
    execution: ['Проект на подконструкция', 'Монтаж', 'Предаване'],
    cover: { alt: 'Жилищна сграда с HPL фасада — placeholder', tone: 'hpl-wood', seed: 6 },
    gallery: [
      { alt: 'Фасада — placeholder', tone: 'hpl-wood', seed: 7 },
      { alt: 'Балкони — placeholder', tone: 'hpl-dark', seed: 8 },
      { alt: 'Детайл — placeholder', tone: 'hpl-wood', seed: 9 },
    ],
    featured: true,
    isPlaceholder: true,
  },
  {
    id: 'p-03',
    slug: 'primeren-obekt-targovski-obekt',
    title: 'Търговски обект',
    location: { city: 'Варна' },
    type: 'retail',
    materials: ['al-bond'],
    services: ['al-bond-montazh', 'proektirane', 'montazh'],
    summary: 'Al Bond фасада и обшивка на козирка.',
    description: `${note} Опишете обекта.`,
    cover: { alt: 'Търговски обект с Al Bond — placeholder', tone: 'acp-graphite', seed: 10 },
    gallery: [
      { alt: 'Фасада — placeholder', tone: 'acp-graphite', seed: 11 },
      { alt: 'Козирка — placeholder', tone: 'acp-bronze', seed: 12 },
    ],
    featured: true,
    isPlaceholder: true,
  },
  {
    id: 'p-04',
    slug: 'primeren-obekt-hotel',
    title: 'Хотел',
    location: { city: 'Бургас' },
    type: 'hotel',
    materials: ['keramika', 'laminam'],
    services: ['keramichni-fasadi', 'ventiliruemi-fasadi', 'proektirane', 'montazh'],
    summary: 'Керамична вентилируема фасада с Laminam във входната зона.',
    description: `${note} Опишете обекта.`,
    cover: { alt: 'Хотел с керамична фасада — placeholder', tone: 'ceramic-stone', seed: 13 },
    gallery: [
      { alt: 'Фасада — placeholder', tone: 'ceramic-stone', seed: 14 },
      { alt: 'Входна зона — placeholder', tone: 'laminam', seed: 15 },
      { alt: 'Детайл — placeholder', tone: 'ceramic-light', seed: 16 },
    ],
    featured: true,
    isPlaceholder: true,
  },
  {
    id: 'p-05',
    slug: 'primeren-obekt-promishlena-sgrada',
    title: 'Промишлена сграда',
    location: { city: 'Стара Загора' },
    type: 'industrial',
    materials: ['al-bond', 'drugi'],
    services: ['okacheni-fasadi', 'fasadni-konstrukcii', 'montazh'],
    summary: 'Окачена фасада с метални касети и Al Bond акценти.',
    description: `${note} Опишете обекта.`,
    cover: { alt: 'Промишлена сграда — placeholder', tone: 'acp-graphite', seed: 17 },
    gallery: [{ alt: 'Фасада — placeholder', tone: 'acp-graphite', seed: 18 }],
    isPlaceholder: true,
  },
  {
    id: 'p-06',
    slug: 'primeren-obekt-rekonstrukciya',
    title: 'Реконструкция на офис сграда',
    location: { city: 'София' },
    type: 'office',
    materials: ['al-bond'],
    services: ['rekonstrukciya-na-fasadi', 'al-bond-montazh', 'proektirane', 'montazh'],
    summary: 'Нова Al Bond облицовка върху съществуваща сграда.',
    description: `${note} За реконструкции добавете снимки „преди“ и „след“ — показват се с интерактивен slider.`,
    challenge: 'Опишете състоянието на сградата преди обновяването.',
    solution: 'Опишете решението.',
    cover: { alt: 'Реконструирана сграда — placeholder', tone: 'acp-bronze', seed: 19 },
    gallery: [{ alt: 'След реконструкцията — placeholder', tone: 'acp-bronze', seed: 20 }],
    beforeAfter: {
      before: { alt: 'Преди — placeholder', tone: 'old-plaster', seed: 21 },
      after: { alt: 'След — placeholder', tone: 'acp-bronze', seed: 21 },
    },
    featured: true,
    isPlaceholder: true,
  },
  {
    id: 'p-07',
    slug: 'primeren-obekt-obshtestvena-sgrada',
    title: 'Обществена сграда',
    location: { city: 'Пловдив' },
    type: 'public',
    materials: ['hpl', 'keramika'],
    services: ['ventiliruemi-fasadi', 'hpl-fasadi', 'keramichni-fasadi', 'montazh'],
    summary: 'Комбинирана вентилируема фасада — HPL и керамика.',
    description: `${note} Опишете обекта.`,
    cover: { alt: 'Обществена сграда — placeholder', tone: 'mixed', seed: 22 },
    gallery: [{ alt: 'Фасада — placeholder', tone: 'hpl-dark', seed: 23 }, { alt: 'Цокъл — placeholder', tone: 'ceramic-stone', seed: 24 }],
    isPlaceholder: true,
  },
  {
    id: 'p-08',
    slug: 'primeren-obekt-shourum',
    title: 'Шоурум',
    location: { city: 'Варна' },
    type: 'retail',
    materials: ['laminam', 'al-bond'],
    services: ['keramichni-fasadi', 'al-bond-montazh', 'montazh'],
    summary: 'Laminam плочи и Al Bond бордове.',
    description: `${note} Опишете обекта.`,
    cover: { alt: 'Шоурум — placeholder', tone: 'laminam', seed: 25 },
    gallery: [{ alt: 'Фасада — placeholder', tone: 'laminam', seed: 26 }],
    isPlaceholder: true,
  },
]

export const getProject = (slug: string) => projects.find((p) => p.slug === slug)
export const featuredProjects = () => projects.filter((p) => p.featured)
